#!/usr/bin/env bash

module="$(basename "$(pwd)")"

target_branch="$(
    grep -A 3 -hIiPs "submodule.+\"$module\"" ../../.gitmodules | \
        grep -ioPs "branch\s*\=\s*\K.+"
)"

case "$(git branch --show-current)" in
    "$target_branch") ;;
    *) git checkout "$target_branch" ;;
esac

git pull
