#!/usr/bin/env bash

# shellcheck disable=SC2154

target_branch="$(
    grep -A 3 -hIiPs "submodule \"$name\"" "$toplevel/.gitmodules" | \
    grep -ioPs "branch\s*\=\s*\K.+"
)"

case "$(git branch --show-current)" in
    "$target_branch") ;;
    *) git checkout "$target_branch" ;;
esac

git pull
